### ISSUE TITLE
ModuleNotFoundError: No module named 'gql.transport.http'

### ISSUE THREAD

**Issue by siupenyau** [hivdb/sierra-client#12]
Hi, thank you for releasing the command line tools. I installed sierrapy by creating an environment in Anaconda3:

conda create -n sierrapy -c bioconda sierrapy python=3.6

I tried the sierrapy fasta command in the environment and I got the following error message:

Traceback (most recent call last):
  File "/home/USER/anaconda3/envs/sierrapy/bin/sierrapy", line 6, in <module>
    from sierrapy.cmds import main
  File "/home/USER/anaconda3/envs/sierrapy/lib/python3.6/site-packages/sierrapy/__init__.py", line 2, in <module>
    from .sierraclient import VERSION, SierraClient
  File "/home/USER/anaconda3/envs/sierrapy/lib/python3.6/site-packages/sierrapy/sierraclient.py", line 8, in <module>
    from gql.transport.http import HTTPTransport
ModuleNotFoundError: No module named 'gql.transport.http'

I found that the gql.transport.http was missing, even the gql.transport module was available. I could not find any source to download gql.transport.http. Would you please provide any suggestion?

With best wishes,

Timothy Ng

**Comment by antoine4ucsd** [comment]
same problem for me. any fix? thank you!

**Comment by philiptzou** [comment]
Hello @siupenyau & @antoine4ucsd, sorry for the late response. The issue was already addressed in commit 13d84e171b4f9d2f28706079f0776dbcace8592e. I just released a new version 0.4.0 on PyPI which includes this fix.

Note that the BioConda repository is maintained by a third party contributor, probably by @ozagordi (https://github.com/hivdb/sierra-client/issues/3#issuecomment-359720417). Let's ask him if we can also upgrade the BioConda version.

**Comment by antoine4ucsd** [comment]
sounds great. will you reach out to @ozagordi or should i? I guess most users are using conda.
thank you for your help ++

**Comment by philiptzou** [comment]
@antoine4ucsd Working on it right now. bioconda/bioconda-recipes#37291

**Comment by antoine4ucsd** [comment]
thank you

**Comment by siupenyau** [comment]
Thank you for your help. Bioconda is great.

**Comment by philiptzou** [comment]
@antoine4ucsd & @siupenyau I'll close this issue since the upgrade (0.4.1) has been deployed to BioConda.

**Comment by antoine4ucsd** [comment]
thank you
