### ISSUE TITLE
Output file name contains zero

### ISSUE THREAD

**Issue by vera-rykalina** [hivdb/sierra-client#16]
# Version
sierrapy --version
SierraPy 0.4.1; Sierra 3.4.2 (2022-12-14); HIVdb HIVDB_9.4 (2022-12-07)

# Command
sierrapy fasta my.fasta -o my.json

# Output 
my.0.json

**Comment by philiptzou** [comment]
Hello @vera-rykalina 

This behavior is expected since the client by default saves results into chunks by `--sharding=100`. You can find the description of the `--sharding` parameter here: https://github.com/hivdb/sierra-client/tree/master/python#input-sequences-fasta-file

**Comment by vera-rykalina** [comment]
Hi Philip,

thanks a lot for your feedback. Sorry, it was indeed not obvious for me that such file name change can be an expected behaviour. The thing is that with this zero an output file name within a Nextflow pipeline is not under control anymore. And this was not the case for version 0.3.0. A final output file name differs from the one which is set.  So, it is still an issue. 

Thanks,
Vera

**Comment by philiptzou** [comment]
@vera-rykalina I see. A `--no-sharding` flag will be added in the next version for disabling this behavior. I'm wondering which pipeline do you use and how many sequences do you normally run in a batch? The pre-0.3.0 version SierraPy went to out-of-memory error when processing dozens of thousands sequences and that's the reason we added this feature.

**Comment by vera-rykalina** [comment]
I use a Nextflow pipeline which I built on my own. We normaly process up to 96 sequences. I was thinking of updating SierraPy to the latest version, but encountered this problem I mentioned above. 

This worked pretty well with version 0.3.0:
[](url)

**Comment by vera-rykalina** [comment]
![Screenshot from 2023-02-16 18-33-42](https://user-images.githubusercontent.com/51401865/219444812-31930ef4-51bd-41e8-b44a-390eb2f3b947.png)

**Comment by philiptzou** [comment]
@vera-rykalina An easy workaround is making the following changes:

```
...
output:
  path "${fasta.getSimpleName()}.0.json"

script:
  """
  sierrapy fasta ${fasta} --sharding 500 -o ${fasta.getSimpleName()}.json
  """
...
```

This workaround can handle up to 500 sequences in a batch. If you want to input more sequences, just increase the number after `--sharding`.

I'll still update the client in the next version to provide the flag `--no-sharding`.

**Comment by Nicolas-Fernandez** [comment]
Dear all,

Encounter same issu as [vera-rykalina](https://github.com/vera-rykalina), with Snakemake pipeline...
We do not "sharding" we process sample one by one, workflows managers do the job.
Input / Output naming control is very important for pipeline succes.

Looking for `--no-sharding` feature :) Thx a lot.

**Comment by Nicolas-Fernandez** [comment]
@vera-rykalina, my ugly turn-around, like...

```
sierrapy fasta -o toto.json toto.fasta && rename 's/.0.json/.json/' *.0.json
```

**Comment by philiptzou** [comment]
This issue has been resolved in SierraPy 0.4.2.

**Comment by Nicolas-Fernandez** [comment]
Dear Philip, just tested, perfect for me !
Thank a lot, have a nice day, best :)
Nico

**Comment by vera-rykalina** [comment]
Hi Philip! 
Many thanks from my side as well. I have just implemented --no-sharding into my pipeline - it works smoothly both locally and on HPC. 
Cheers,
Vera.
