### ISSUE TITLE
Indicating sites that are not callable with the patterns subcommand

### ISSUE THREAD

**Issue by kes1smmn** [hivdb/sierra-client#4]
In the `patterns` subcommand is it possible to indicate sites that are not callable?

The `fasta` subcommand has a nice Warning if an input sequence has masked bases.
```
"validationResults": [
      {
        "level": "SEVERE_WARNING",
        "message": "The IN sequence contains just 74 codons, which is not sufficient for a comprehensive interpretation."
      }
    ],
```

Using the `patterns` subcommand I tried to indicate uncallable sites with an `X` (e.g.`RT:Q269X`) but It did not produce the desired effect.

**Comment by philiptzou** [comment]
Hi @kes1smmn,

This issue should belong to Sierra server (https://github.com/hivdb/sierra) but not the client, so I'll close this issue right now. You are welcome to open one in the Sierra server repository.

For the question: currently we don't have the parameters to indicate the coverage for mutations input. However it is possible that we add such feature in the future.
