### ISSUE TITLE
Install Sierrapy on CentOS

### ISSUE THREAD

**Issue by el1jaC** [hivdb/sierra-client#5]
Hi,
there is a way to install sierrapy on CentOS 6.10?
I've tried every possibilities, but for example, with the command pip install sierrapy, a python error is returned:

> Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-vTN_om/gql/setup.py", line 26, in <module>
        packages=find_packages(include=["gql*"]),
    TypeError: find_packages() got an unexpected keyword argument 'include'
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vTN_om/gql

Thanks in advance,
Elia

**Comment by philiptzou** [comment]
Hi @el1jaC Sorry I just noticed this one. Have you figured it out yourself?

**Comment by el1jaC** [comment]
Hi,
yes...it was a compatibility problem with default python version of centos.

**Comment by philiptzou** [comment]
@el1jaC Thanks. I'll make a note of it.
