### ISSUE TITLE
More than a issue is a question

### ISSUE THREAD

**Issue by AAMCgenomics** [hivdb/sierra-client#6]
We had an implementation that take xml output from hivdb stanford webpage for donwstream analysis, and reporting.
However I would like to know How can I produce the same output with sierrapy?

If there a way to print xml output instead of json?

I really appreciate any  recommendations.

Thank you in advance.

**Comment by philiptzou** [comment]
Hi @AAMCgenomics. Unfortunately there's no way to get XML output from SierraPy.
